/* 
 The Fibbonacci sequence is a never ending numerical sequence generated by
 adding the previous two numbers together to get the next number in the sequence.
 For convience the sequence starts with two 1's. So the first few numbers are
 as follows:

 1,1,2,3,5,8,13,21,34 ... 

 Complete the function fibbonacci below such that it accepts an integer
 input parameter n and returns the nth number in the sequence. So

 fibbonacci(0); // should return 1
 fibbonacci(1); // should return 1
 fibbonacci(2); // should return 2
 fibbonacci(3); // should return 3
 fibbonacci(4); // should return 5
*/

function fibbonacci(n) {
	// Finish this function
}

// Test function, checks the first few known values.
function testFib() {
	var fibTests = [1,1,2,3,5,8,13,21,34];
	var allPassing = true;
	
	for(var i = 0; i < fibTests.length; i++) {
		if(fibbonacci(i) !== fibTests[i]) {
			allPassing = false;
			console.log("failure for " + i + ".\n  Expected: " + fibTests[i] + "\n  Got: " + fibbonacci(i) + "\n");
		}
	}

	if(allPassing) {
		console.log("All tests passed");
	}
}

// Calls the test function
testFib();